name: task_app_shared
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: newman <iorgachov1998@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  json_serializable: ^3.1.0
  built_value: ^6.7.0
  built_collection: ^4.2.2
  bloc: ^0.14.4

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  build_runner: ^1.5.0
  built_value_generator: ^6.7.0

